### PR TITLE
Added supported for CLI margins option.

### PR DESCRIPTION
**Pull request by Niremizov**
Bug reported here https://github.com/camelot-dev/camelot/issues/499
https://github.com/camelot-dev/camelot/pull/500

### CODE REVIEW

**Comment by bosd** [comment]
@Niremizov Thanks for your contribution.
CI should be fixed now. Can you please rebase?

Is it possible to add some unit tests?

**Comment by Niremizov** [comment]
Tried rebase, but now too many commits are in pull request list. Seems it would be easier to close this pull and create new one. Would try this later.

**Comment by Niremizov** [comment]
See cmt above.

**Comment by Niremizov** [comment]
New pull is here https://github.com/py-pdf/pypdf_table_extraction/pull/111
Still tests are needed.

**Comment by Niremizov** [comment]
Added tests

**Pull request closed without merging**
