### PR TITLE
Added supported for CLI margins option.

### PR DESCRIPTION
**Pull request by Niremizov**
Bug reported here https://github.com/camelot-dev/camelot/issues/499
Pull to original repository https://github.com/camelot-dev/camelot/pull/500 (commits differs, cause to rebase issues)

### CODE REVIEW

**Comment by Niremizov** [comment]
Hope that now finally fixed tests.

**Comment by bosd** [comment]
Let's see the results 😉
Again thanks for your work on this!

**Comment by bosd** [comment]
Tests are good now, can you please squash your lats 2 commits?
(so the fixes are included in the add tests commit)

**Comment by Niremizov** [comment]
Done

**Review by bosd — APPROVED** [review]

**Pull request merged**
