### PR TITLE
[FIX]:  codecov action

### PR DESCRIPTION
**Pull request by bosd**
as discovered in: https://github.com/py-pdf/pypdf_table_extraction/issues/29#issuecomment-2292230072

### CODE REVIEW

**Comment by bosd** [comment]
There are still some issues:
```
warning - 2024-08-21 06:07:36,242 -- xcrun is not installed or can't be found.
warning - 2024-08-21 06:07:36,261 -- No gcov data found.
warning - 2024-08-21 06:07:36,262 -- coverage.py is not installed or can't be found.

```

**Comment by bosd** [comment]
```
gpg:                using RSA key 27034E7FDB850E0BBC2C62FF806BB28AED779869
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2703 4E7F DB85 0E0B BC2C  62FF 806B B28A ED77 9869

```

**Comment by bosd** [comment]
Let's proceed with this one.
The reported errors seems to be related to the nox setup.
Let's hanlde that in a seperate issue, if still exsists.

Closes #29

**Comment by foarsitter** [comment]
Good job @bosd!

**Pull request merged**
